# Generated by Django 5.1.5 on 2025-02-06 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('imagem_perfil', models.ImageField(blank=True, null=True, upload_to='uploads/fotoperfil/')),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='uploads/fotocapa/')),
                ('fonte', models.CharField(default='fonte-3', max_length=10)),
                ('cor', models.CharField(default='cor-1', max_length=10)),
                ('background', models.CharField(default='light', max_length=10)),
                ('contatos', models.ManyToManyField(to='perfil.perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
