# Generated by Django 5.1.5 on 2025-02-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='contatos',
            field=models.ManyToManyField(blank=True, null=True, to='perfil.perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='fotocapa/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotoPerfil/'),
        ),
    ]
