# Generated by Django 5.1.5 on 2025-03-22 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curtida_comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_curtida', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas_comentarios', to='perfil.comentario')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas_comentarios', to='perfil.perfil')),
            ],
            options={
                'unique_together': {('perfil', 'comentario')},
            },
        ),
    ]
