# Generated by Django 5.1.5 on 2025-03-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_curtida_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='comentario',
        ),
    ]
