# Generated by Django 5.1.5 on 2025-02-06 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_contatos_alter_perfil_imagem_capa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='contatos',
            field=models.ManyToManyField(to='perfil.perfil'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('data_postagem', models.DateTimeField(auto_now=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='postagem/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='perfil.perfil')),
            ],
        ),
    ]
