# Generated by Django 5.1.5 on 2025-03-22 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_remove_notificacao_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.comentario'),
        ),
    ]
