# Generated by Django 5.1.5 on 2025-02-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_convite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='contatos',
            field=models.ManyToManyField(blank=True, null=True, to='perfil.perfil'),
        ),
    ]
