# Generated by Django 5.1.5 on 2025-02-07 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_perfil_salvos_comentario_curtida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='salvos',
        ),
    ]
