# Generated by Django 5.1.5 on 2025-02-07 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_remove_perfil_salvos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('curtida', 'Curtida'), ('comentario', 'Comentário'), ('amizade', 'Solicitação de Amizade')], max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('perfil_acionador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='perfil.perfil')),
                ('perfil_notificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='perfil.perfil')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.post')),
            ],
        ),
    ]
