# Generated by Django 5.1.5 on 2025-02-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('curtida', 'Curtiu'), ('comentario', 'Comentário'), ('amizade', 'Solicitação de Amizade')], max_length=20),
        ),
    ]
