# Generated by Django 5.1.5 on 2025-02-09 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0010_alter_notificacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('curtida', 'Curtiu'), ('comentario', 'Comentou'), ('amizade', 'Solicitação de Amizade')], max_length=20),
        ),
        migrations.CreateModel(
            name='Marcador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_marcada', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcados', to='perfil.perfil')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcados', to='perfil.post')),
            ],
            options={
                'unique_together': {('perfil', 'post')},
            },
        ),
    ]
